# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

name: CI

on:
    push:
        branches: [main, "feature/*"]
    pull_request:
        branches: [main, "feature/*"]
    workflow_dispatch:

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-22.04, macOS-13, macos-14, windows-2022]
                board: [stm32h735g-dk, stm32h747i-disco]

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4          
              with:
                sparse-checkout: ${{ matrix.board }}
            - uses: seanmiddleditch/gha-setup-ninja@v5
            - name: Install GNU Arm Embedded Toolchain
              uses: carlosperate/arm-none-eabi-gcc-action@v1
              with:
                release: '13.3.Rel1'
            - name: CMake configure
              working-directory: ${{ matrix.board }}
              run: |
                  cmake --preset Debug
            - name: CMake build
              working-directory: ${{ matrix.board }}
              run: |
                  cmake --build --preset Debug
